import type { Metadata } from "next";
import {Providers} from "./providers";
import { Geist, Geist_Mono } from "next/font/google";
import {Link} from "@nextui-org/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}); 

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
        <Link style={{ position:"fixed", bottom:"10px", left:"10px", backgroundColor:"black", borderRadius:"8px", color:"white", padding:"16px", margin:"8px"}} href="/">
          HOME
        </Link>
        </Providers>
      </body>
    </html>
  );
}
